### PR TITLE
Remove Cruiser and Destroyer and replace with Clipper and Dinghy.

### PR DESCRIPTION
**Pull request by TravisWhitehead**
This just removes and adds the ships that the assignment requires. It's pretty straightforward.

### CODE REVIEW

**Comment by ghost** [comment]
Code looks good. Did you test compiling and running it?

**Comment by TravisWhitehead** [comment]
Yeah I tested it, although I did overlook one thing... Commit inbound.

**Comment by TravisWhitehead** [comment]
It's good to go, now. (I tested scanning w/ stealth, one-hit sink for civvie ships, and gameplay overall.)

**Comment by ghost** [comment]
Excellent. Merging.

**Comment by FiscalClifford** [comment]
Solid Pull, Clipper and Dinghy can be identified as civilian ships by Ship.type.equals("ship") while Military ships are the same except "militaryShip"

**Pull request merged**
